### ISSUE TITLE
ResultSet.fromJson cannot parse timezones 

### ISSUE THREAD

**Issue by hyyan** [BasisHub/components#168]
**JSON**
```json
[
  {
    "FIRST_NAME": "Melody",
    "LAST_NAME": "Shields",
    "AGE": 28,
    "COUNTRY": "Barbados",
    "COMPANY": "LUNCHPAD",
    "EMAIL": "melody.shields@lunchpad.io",
    "IS_ACTIVE": true,
    "BALANCE": 4010,
    "PHONE": 19510953420,
    "ADDRESS": "397 Langham Street, Frizzleburg, Utah, 4386",
    "CREATED_AT": "2020-02-18T05:00:49Z",
    "LAST_LOGIN": "2020-01-25",
    "LAST_SEEN": "09:14:53",
    		"meta": {
			"FIRST_NAME": {
				"ColumnType": "12"
			},
			"LAST_NAME": {
				"ColumnType": "12"
			},
			"AGE": {
				"ColumnType": "8"
			},
			"COUNTRY": {
				"ColumnType": "12"
			},
			"EMAIL": {
				"ColumnType": "12"
			},
			"IS_ACTIVE": {
				"ColumnType": "16"
			},
			"BALANCE": {
				"ColumnType": "8"
			},
			"PHONE": {
				"ColumnType": "8"
			},
			"ADDRESS": {
				"ColumnType": "12"
			},
			"CREATED_AT": {
				"ColumnType": "93"
			},
			"LAST_LOGIN": {
				"ColumnType": "91"
			},
			"LAST_SEEN": {
				"ColumnType": "92"
			}
		}
  }
]
```

**In BBj 19:11** 

```java
ResultSet.fromJson(json!).toJson()
```

**Error** 

```
[13:22:36.844+0100] SYSERR  com.basis.startup.type.BBjException: java.lang.NumberFormatException: For input string: "49Z"
[13:22:36.844+0100] SYSERR  	at com.basis.bbj.processor.program.type.SignatureHandler.throwBBj(SignatureHandler.java:285)
[13:22:36.844+0100] SYSERR  	at com.basis.bbj.processor.program.type.SignatureHandler.dispatch(SignatureHandler.java:291)
[13:22:36.845+0100] SYSERR  	at com.basis.bbj.processor.program.type.JavaType$JavaSignature.dispatch(JavaType.java:7)
[13:22:36.845+0100] SYSERR  	at com.basis.bbj.processor.program.type.SignatureHandler.handleSignature(SignatureHandler.java:223)
[13:22:36.845+0100] SYSERR  	at com.basis.bbj.processor.instruction.a.k.a(k.java:29)
[13:22:36.845+0100] SYSERR  	at com.basis.bbj.processor.instruction.ee.a(ee.java:19)
[13:22:36.845+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.cw.L(cw.java:2628)
[13:22:36.845+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.cw.I(cw.java:2660)
[13:22:36.845+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.cw.run(cw.java:2890)
[13:22:36.845+0100] SYSERR  	at com.basis.util.common.BasisThread.run(BasisThread.java:15)
[13:22:36.845+0100] SYSERR  Caused by: java.lang.NumberFormatException: For input string: "49Z"
[13:22:36.845+0100] SYSERR  	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[13:22:36.845+0100] SYSERR  	at java.lang.Integer.parseInt(Integer.java:580)
[13:22:36.845+0100] SYSERR  	at java.lang.Integer.parseInt(Integer.java:615)
[13:22:36.845+0100] SYSERR  	at java.sql.Timestamp.valueOf(Timestamp.java:259)
[13:22:36.845+0100] SYSERR  	at com.basiscomponents.db.util.DataFieldConverter.convertType(DataFieldConverter.java:212)
[13:22:36.845+0100] SYSERR  	at com.basiscomponents.db.DataField.convertType(DataField.java:527)
[13:22:36.845+0100] SYSERR  	at com.basiscomponents.db.util.DataRowFromJsonProvider.createDataFields(DataRowFromJsonProvider.java:160)
[13:22:36.845+0100] SYSERR  	at com.basiscomponents.db.util.DataRowFromJsonProvider.fromJson(DataRowFromJsonProvider.java:69)
[13:22:36.845+0100] SYSERR  	at com.basiscomponents.db.DataRow.fromJson(DataRow.java:1416)
[13:22:36.845+0100] SYSERR  	at com.basiscomponents.db.ResultSet.fromJson(ResultSet.java:2123)
[13:22:36.845+0100] SYSERR  	at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source)
[13:22:36.845+0100] SYSERR  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:22:36.845+0100] SYSERR  	at java.lang.reflect.Method.invoke(Method.java:498)
[13:22:36.846+0100] SYSERR  	at com.basis.startup.LoadLibrary.invokeMethod(LoadLibrary.java:1)
[13:22:36.846+0100] SYSERR  	at com.basis.startup.LoadLibrary.invokeMethodInContext(LoadLibrary.java:10)
[13:22:36.846+0100] SYSERR  	at com.basis.util.common.security.a5.invokeMethod(a5.java:48)
[13:22:36.846+0100] SYSERR  	at com.basis.bbj.processor.program.type.JavaType$JavaMethod.invoke(JavaType.java)
[13:22:36.846+0100] SYSERR  	at com.basis.bbj.processor.program.type.SignatureHandler.dispatch(SignatureHandler.java:64)
[13:22:36.846+0100] SYSERR  	... 8 more
[13:22:36.846+0100] SYSERR  Date: Fri Mar 13 13:22:36 CET 2020
```

@StephanWald

**Comment by hyyan** [comment]
working in BBj 20.10
