### ISSUE TITLE
ResultSet.fromJson cannot parse time columns 

### ISSUE THREAD

**Issue by hyyan** [BasisHub/components#169]
**JSON**

```json
[
  {
    "FIRST_NAME": "Melody",
    "LAST_NAME": "Shields",
    "AGE": 28,
    "COUNTRY": "Barbados",
    "COMPANY": "LUNCHPAD",
    "EMAIL": "melody.shields@lunchpad.io",
    "IS_ACTIVE": true,
    "BALANCE": 4010,
    "PHONE": 19510953420,
    "ADDRESS": "397 Langham Street, Frizzleburg, Utah, 4386",
    "CREATED_AT": "2020-02-18T05:00:49Z",
    "LAST_LOGIN": "2020-01-25",
    "LAST_SEEN": "09:14:53",
    		"meta": {
			"FIRST_NAME": {
				"ColumnType": "12"
			},
			"LAST_NAME": {
				"ColumnType": "12"
			},
			"AGE": {
				"ColumnType": "8"
			},
			"COUNTRY": {
				"ColumnType": "12"
			},
			"EMAIL": {
				"ColumnType": "12"
			},
			"IS_ACTIVE": {
				"ColumnType": "16"
			},
			"BALANCE": {
				"ColumnType": "8"
			},
			"PHONE": {
				"ColumnType": "8"
			},
			"ADDRESS": {
				"ColumnType": "12"
			},
			"CREATED_AT": {
				"ColumnType": "12"
			},
			"LAST_LOGIN": {
				"ColumnType": "91"
			},
			"LAST_SEEN": {
				"ColumnType": "92"
			}
		}
  }
]
```

**In BBj 19:11**

```
ResultSet.fromJson(json!).toJson()
```

**Error**

```
[13:24:27.227+0100] SYSERR  com.basis.startup.type.BBjException: com.basiscomponents.db.exception.DataFieldNotFoundException: Field LAST_SEEN does not exist
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.program.type.SignatureHandler.throwBBj(SignatureHandler.java:285)
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.program.type.SignatureHandler.dispatch(SignatureHandler.java:291)
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.program.type.JavaType$JavaSignature.dispatch(JavaType.java:7)
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.program.type.SignatureHandler.handleSignature(SignatureHandler.java:223)
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.instruction.a.k.a(k.java:29)
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.instruction.ee.a(ee.java:19)
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.cw.L(cw.java:2628)
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.cw.I(cw.java:2660)
[13:24:27.227+0100] SYSERR  	at com.basis.bbj.processor.instruction.c.cw.run(cw.java:2890)
[13:24:27.227+0100] SYSERR  	at com.basis.util.common.BasisThread.run(BasisThread.java:15)
[13:24:27.227+0100] SYSERR  Caused by: com.basiscomponents.db.exception.DataFieldNotFoundException: Field LAST_SEEN does not exist
[13:24:27.227+0100] SYSERR  	at com.basiscomponents.db.DataRow.getField(DataRow.java:370)
[13:24:27.227+0100] SYSERR  	at com.basiscomponents.db.DataRow.getField(DataRow.java:346)
[13:24:27.227+0100] SYSERR  	at com.basiscomponents.db.DataRow.setFieldAttribute(DataRow.java:744)
[13:24:27.227+0100] SYSERR  	at com.basiscomponents.db.DataRow.lambda$setFieldAttributes$2(DataRow.java:1421)
[13:24:27.227+0100] SYSERR  	at java.util.HashMap.forEach(HashMap.java:1289)
[13:24:27.227+0100] SYSERR  	at com.basiscomponents.db.DataRow.setFieldAttributes(DataRow.java:1421)
[13:24:27.228+0100] SYSERR  	at com.basiscomponents.db.util.DataRowFromJsonProvider.createDataFields(DataRowFromJsonProvider.java:203)
[13:24:27.228+0100] SYSERR  	at com.basiscomponents.db.util.DataRowFromJsonProvider.fromJson(DataRowFromJsonProvider.java:69)
[13:24:27.228+0100] SYSERR  	at com.basiscomponents.db.DataRow.fromJson(DataRow.java:1416)
[13:24:27.228+0100] SYSERR  	at com.basiscomponents.db.ResultSet.fromJson(ResultSet.java:2123)
[13:24:27.228+0100] SYSERR  	at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source)
[13:24:27.228+0100] SYSERR  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:24:27.228+0100] SYSERR  	at java.lang.reflect.Method.invoke(Method.java:498)
[13:24:27.228+0100] SYSERR  	at com.basis.startup.LoadLibrary.invokeMethod(LoadLibrary.java:1)
[13:24:27.228+0100] SYSERR  	at com.basis.startup.LoadLibrary.invokeMethodInContext(LoadLibrary.java:10)
[13:24:27.228+0100] SYSERR  	at com.basis.util.common.security.a5.invokeMethod(a5.java:48)
[13:24:27.228+0100] SYSERR  	at com.basis.bbj.processor.program.type.JavaType$JavaMethod.invoke(JavaType.java)
[13:24:27.228+0100] SYSERR  	at com.basis.bbj.processor.program.type.SignatureHandler.dispatch(SignatureHandler.java:64)
[13:24:27.228+0100] SYSERR  	... 8 more
[13:24:27.228+0100] SYSERR  Date: Fri Mar 13 13:24:27 CET 2020
```
@StephanWald

**Comment by hyyan** [comment]
working in BBj 20.10
